// capability.tsx
export const CAPABILITIES = {
  'Front-end': [
    'Strong Fundamentals – Solid HTML, CSS, JS basics',
    'Framework Proficiency – Skilled in React/Angular/Vue',
    'Problem-Solving – Breaks problems into steps',
    'Debugging Curiosity – Uses tools, digs into issues',
    'Performance Mindset – Cares about speed & accessibility',
    'Clear Communication – Explains simply, asks questions',
    'Collaboration & Humility – Open to feedback, team-first',
    'Growth Attitude – Always learning & adapting',
    'Product Thinking – Builds with users/business in mind',
    'Attention to Detail – Spots edge cases, polishes UI',
  ],
  'Back-End': [
    'Strong Fundamentals – Data structures, algorithms, OOP',
    'API Design – RESTful, GraphQL, gRPC',
    'Database Skills – SQL & NoSQL expertise',
    'Security Awareness – Auth, encryption, validation',
    'Scalability Thinking – Handles high traffic & load',
    'Error Handling – Robust logging & monitoring',
    'Performance Tuning – Query optimization, caching',
    'DevOps Awareness – CI/CD, container basics',
    'Collaboration – Works closely with frontend & QA',
    'Growth Attitude – Adapts to new frameworks & stacks',
  ],
  'Full-stack': [
    'End-to-End Knowledge – Can build frontend + backend',
    'API Integration – Connects UI with backend services',
    'Database Handling – CRUD ops, schema design',
    'Problem-Solving – Tackles cross-layer issues',
    'Performance Focus – Optimizes across stack',
    'Version Control – Git workflows, branching',
    'Collaboration – Bridges frontend & backend teams',
    'Deployment Knowledge – Basic cloud & CI/CD',
    'Adaptability – Switches between UI & APIs easily',
    'User-Centric Mindset – Balances UI and system design',
  ],
  DevOps: [
    'CI/CD Expertise – Automates builds & deployments',
    'Containerization – Docker & Kubernetes skills',
    'Cloud Platforms – AWS, Azure, GCP knowledge',
    'Monitoring – Prometheus, Grafana, ELK stack',
    'Scripting – Bash, Python for automation',
    'Infrastructure as Code – Terraform, Ansible',
    'Security Practices – Secrets management, audits',
    'Troubleshooting – Debugs infra & pipeline issues',
    'Collaboration – Works with developers & QA',
    'Scalability Thinking – Ensures reliable infra growth',
  ],
  'AI/ML': [
    'Math & Stats – Linear algebra, probability basics',
    'ML Fundamentals – Regression, classification, clustering',
    'Deep Learning – Neural networks, CNNs, RNNs',
    'Data Handling – Cleaning, preprocessing, feature engineering',
    'Programming – Python, NumPy, Pandas, PyTorch/TensorFlow',
    'Model Evaluation – Metrics, cross-validation',
    'Deployment – Serving models with APIs',
    'Scalability – Big data tools, distributed training',
    'Research Mindset – Reads papers, explores new methods',
    'Ethics Awareness – Bias, fairness, explainability',
  ],
} as const;

export type Role = keyof typeof CAPABILITIES;
