import {
  FailedInterviewResponse,
  SuccessInterviewScheduleResponse,
} from '@/types/interview';

export const fake_slotBookingResponse: SuccessInterviewScheduleResponse = {
  success: true,
  message: 'Interview scheduled successfully',
  data: {
    candidateId: '4e6d7c95-f3ac-4381-923c-d52e00f00728',
    userId: '29df8bdb-5cc2-4e74-bd64-042096386b84',
    interview: {
      candidateId: '4e6d7c95-f3ac-4381-923c-d52e00f00728',
      interviewerId: '4ab21e92-b031-4c57-9c59-e511224f5172',
      requestedSlots: [
        {
          endTime: '2025-08-25T11:00:00Z',
          timezone: 'UTC',
          startTime: '2025-08-25T10:00:00Z',
        },
        {
          endTime: '2025-08-26T15:00:00Z',
          timezone: 'UTC',
          startTime: '2025-08-26T14:00:00Z',
        },
      ],
      scheduledSlot: {
        startTime: '2025-08-26T14:00:00Z',
        endTime: '2025-08-26T15:00:00Z',
        timezone: 'UTC',
      },
      interviewType: 'technical',
      status: 'scheduled',
      notes: 'Prefer technical interview focused on React and Node.js',
      durationMinutes: 60,
      meetingLink: null,
      meetingId: null,
      feedback: null,
      rating: null,
      rejectionReason: null,
      scheduledAt: null,
      completedAt: null,
      cancelledAt: null,
      id: '3599c6ca-00da-4461-8f1d-9d2954852661',
      availableAlternativeSlots: [],
      resumeShared: true,
      calendarInviteSent: true,
      reminderSent: false,
      createdAt: '2025-08-21T12:36:03.863Z',
      updatedAt: '2025-08-21T12:36:03.888Z',
    },
    scheduledSlot: {
      startTime: '2025-08-26T14:00:00Z',
      endTime: '2025-08-26T15:00:00Z',
      timezone: 'UTC',
    },
    status: 'scheduled',
  },
};

export const fake_slotBookingAlternative: FailedInterviewResponse = {
  success: false,
  message: 'No interviewers available for the requested time slots',
  alternativeSlots: [],
  data: {
    candidateId: '4e6d7c95-f3ac-4381-923c-d52e00f00728',
    userId: '29df8bdb-5cc2-4e74-bd64-042096386b84',
    requestedSlots: [
      {
        startTime: '2025-08-25T10:00:00Z',
        endTime: '2025-08-25T11:00:00Z',
        timezone: 'UTC',
      },
      {
        startTime: '2025-08-26T14:00:00Z',
        endTime: '2025-08-26T16:00:00Z',
        timezone: 'UTC',
      },
    ],
    alternativeSlots: [
      {
        startTime: '2025-08-25T09:00:00.000Z',
        endTime: '2025-08-25T10:00:00.000Z',
        timezone: 'UTC',
      },
      {
        startTime: '2025-08-25T11:00:00.000Z',
        endTime: '2025-08-25T12:00:00.000Z',
        timezone: 'UTC',
      },
      {
        startTime: '2025-08-25T12:00:00.000Z',
        endTime: '2025-08-25T13:00:00.000Z',
        timezone: 'UTC',
      },
      {
        startTime: '2025-08-25T13:00:00.000Z',
        endTime: '2025-08-25T14:00:00.000Z',
        timezone: 'UTC',
      },
      {
        startTime: '2025-08-25T14:00:00.000Z',
        endTime: '2025-08-25T15:00:00.000Z',
        timezone: 'UTC',
      },
    ],
    availableInterviewers: [],
  },
};

export const fake_resume_data = {
  jd_s3_key: 'Jr. AIML JD.docx',
  resume_data: {
    experience: [
      {
        title: 'Automation Test Lead',
        company: 'Wipro LIMITED',
        duration: 'December 2022 - Current',
        start_date: '2022-12',
        end_date: 'Present',
        description:
          'UI Automation with Cypress/Selenium, API Automation with Cypress and Rest Assured, Business Analysis, SRS preparation, Test case preparation, Web Application Testing, Process Automation',
        responsibilities: [
          'UI Automation with Cypress/Selenium',
          'API Automation with Cypress and Rest Assured',
          'Business Analysis',
          'SRS preparation',
          'Test case preparation',
          'Web Application Testing',
          'Process Automation',
        ],
      },
      {
        title: 'Automation Test Analyst',
        company: 'TCS LIMITED',
        duration: 'August 2019 - December 2021',
        start_date: '2019-08',
        end_date: '2021-12',
      },
      {
        title: 'SENIOR TEST ENGINEER',
        company: 'INFOSYS LIMITED',
        duration: 'July 2014 - July 2019',
        start_date: '2014-07',
        end_date: '2019-07',
      },
    ],
    projects: [
      {
        name: 'UI Automation with Cypress/ Selenium',
        description: 'Automating UI testing using Cypress and Selenium',
        technologies: ['Cypress', 'Selenium'],
        duration: 'December 2022 - Current',
      },
      {
        name: 'API Automation with Cypress and Rest Assured',
        description: 'Automating API testing using Cypress and Rest Assured',
        technologies: ['Cypress', 'Rest Assured'],
        duration: 'August 2019 - December 2021',
      },
    ],
    skills: {
      technical: [
        'Java',
        'JavaScript',
        'Selenium',
        'Cypress',
        'BDD',
        'Cucumber',
        'Rest Assured',
        'Jenkins',
        'AWS',
        'MySQL',
        'Mongo DB',
      ],
      soft: ['Business Analysis', 'Process Automation'],
      languages: ['English', 'Hindi', 'Malayalam', 'Tamil'],
      certifications: [
        'Certificate of Special Recognition from Costco client',
        'Certificate of Appreciation from Walgreens client',
        'Trinfy ACE Award',
        'Infosys Insta Award',
      ],
      tools: ['Jira', 'Azure ADO', 'HP-ALM', 'Test rail', 'Gcp'],
      project_management: ['Agile'],
    },
  },
  num_questions: 20,
};
export const fake_jd_s3_key = 'Jr. AIML JD.docx';

export const publishedCandidates = [
  {
    id: '9e9601f3-2f1e-45ac-96f5-956a4d549030',
    status: 'published',
    createdAt: '2025-09-09T13:10:55.427Z',
    candidate: {
      id: '9e9601f3-2f1e-45ac-96f5-956a4d549030',
      user: {
        id: '1661ed33-3f48-4f4a-8500-62fe17a63732',
        email: 'test1@yopmail.com',
        firstName: 'test',
        lastName: '',
        profilePic: null,
      },
      roleTitle: 'Devops',
      summary:
        'Results-oriented Senior Full Stack Developer and Technical Lead with over 11 years of experience spearheading cross-functional teams to deliver high-performance web and mobile applications. Proficient in React.js, Node.js, and AWS cloud technologies, adept at mentoring developers and fostering technical excellence. Skilled in end-to-end product development for US-based startups, driving enhanced user engagement and business growth through innovative solutions.',
      currentDesignation: 'devops',
      currentCompany: '',
      expectedSalary: 0,
      experienceYears: 0,
      skills: [],
      currencyType: 'INR',
      workMode: ['remote'],
      preferredLocations: ['Bangalore, India'],
      location: 'Lucknow, India',
    },
  },
  {
    id: '11ffe938-746d-45f6-a6db-b62f68ecd65b',
    status: 'published',
    createdAt: '2025-09-09T13:33:53.749Z',
    candidate: {
      id: '11ffe938-746d-45f6-a6db-b62f68ecd65b',
      user: {
        id: 'c54cc3d3-f6f5-4418-b554-682df876d619',
        email: 'test2@yopmail.com',
        firstName: 'test',
        lastName: '',
        profilePic:
          'https://faujx-dev.s3.amazonaws.com/users/c54cc3d3-f6f5-4418-b554-682df876d619/profile-pic/profile-pic',
      },
      roleTitle: 'Front-end',
      summary:
        'Seasoned Senior Full Stack Developer and Technical Lead with over 11 years of experience spearheading cross-functional teams to deliver innovative web and mobile applications. Proficient in React.js, Node.js, and AWS cloud technologies, known for mentoring teams and fostering technical excellence. Proven track record of managing end-to-end product development for US startups, enhancing user engagement, and driving business growth through strategic technical solutions.',
      currentDesignation: 'Lead Developer',
      currentCompany: 'TechTory (US Client)',
      expectedSalary: 0,
      experienceYears: 12,
      skills: [
        'React.js',
        'Node.js',
        'AWS',
        'JavaScript',
        'TypeScript',
        'HTML5',
        'CSS3',
        'Redux',
        'jQuery',
        'Express.js',
        'Python',
        'RESTful APIs',
        'GraphQL',
        'Microservices Architecture',
        'MongoDB',
        'MS SQL Server',
        'PostgreSQL',
        'Redis',
        'Lambda',
        'EC2',
        'S3',
        'Amplify',
        'Google Cloud Platform (GCP)',
        'Docker',
        'CI/CD Pipelines',
        'Git',
        'Test-Driven Development',
        'Code Reviews',
        'Performance Optimization',
        'WebSocket',
        'Socket.io',
        'AJAX',
        'Stripe API',
        'SSO Integration',
        'React Native',
        'Next.js',
        'Angular',
        'E-commerce',
        'Agile',
        'Scrum',
        'English',
        'Hindi',
      ],
      currencyType: 'INR',
      workMode: ['remote'],
      preferredLocations: ['Kerala', 'India'],
      location: 'San Francisco, CA',
    },
  },
  {
    id: '4bd28a33-f349-4322-9412-d32e00f843c3',
    status: 'published',
    createdAt: '2025-09-11T12:09:26.524Z',
    candidate: {
      id: '4bd28a33-f349-4322-9412-d32e00f843c3',
      user: {
        id: 'e413eada-326d-423f-bdb4-8b31e2b68952',
        email: 'test-test13@yopmail.com',
        firstName: 'test',
        lastName: '',
        profilePic:
          'https://faujx-dev.s3.amazonaws.com/users/e413eada-326d-423f-bdb4-8b31e2b68952/profile-pic/profile-pic',
      },
      roleTitle: 'Front-end',
      summary:
        'Seasoned Senior Full Stack Developer and Technical Lead with over 11 years of experience spearheading cross-functional teams to deliver cutting-edge web and mobile applications. Proficient in React.js, Node.js, and AWS cloud technologies, adept at mentoring developers and fostering technical excellence. Proven track record of managing end-to-end product development for US-based startups, driving enhanced user engagement and business expansion.',
      currentDesignation: 'Lead Developer',
      currentCompany: 'TechTory (US Client)',
      expectedSalary: 0,
      experienceYears: 12,
      skills: [
        'React.js',
        'Node.js',
        'AWS',
        'JavaScript',
        'HTML5',
        'CSS3',
        'Redux',
        'TypeScript',
        'Angular',
        'RESTful APIs',
        'GraphQL',
        'MongoDB',
        'MS SQL Server',
        'PostgreSQL',
        'Redis',
        'Lambda',
        'EC2',
        'S3',
        'Amplify',
        'Google Cloud Platform',
        'Docker',
        'CI/CD Pipelines',
        'Git',
        'Test-Driven Development',
        'Code Reviews',
        'Performance Optimization',
        'Socket.io',
        'ASP.NET',
        'jQuery',
        'AJAX',
        'Jira',
        'VS Code',
        'React Native',
        'Next.js',
        'Express.js',
        'E-commerce',
        'Healthcare',
        'FinTech',
        'Agile',
        'Scrum',
        'English',
        'Hindi',
      ],
      currencyType: 'INR',
      workMode: ['remote'],
      preferredLocations: ['Bangalore', 'India'],
      location: 'Lucknow, India',
    },
  },
  {
    id: 'f5f65021-2225-4a32-a9a4-eb8854b038dd',
    status: 'published',
    createdAt: '2025-09-11T12:53:51.322Z',
    candidate: {
      id: 'f5f65021-2225-4a32-a9a4-eb8854b038dd',
      user: {
        id: 'c2b2b948-ca70-4a93-8842-13908f6d2d5c',
        email: 'test-test14@yopmail.com',
        firstName: 'testtet',
        lastName: '',
        profilePic: null,
      },
      roleTitle: 'Devops',
      summary:
        'Results-driven Senior Full Stack Developer and Technical Lead with 11+ years of experience leading cross-functional teams to deliver scalable web and mobile applications. Proficient in React.js, Node.js, and AWS cloud technologies, known for mentoring developers and fostering technical excellence. Successfully managed end-to-end product development for US-based startups, driving improved user engagement and business growth through innovative solutions.',
      currentDesignation: 'Lead Developer',
      currentCompany: 'TechTory',
      expectedSalary: 0,
      experienceYears: 12,
      skills: [
        'React.js',
        'Node.js',
        'AWS',
        'JavaScript',
        'TypeScript',
        'HTML5',
        'CSS3',
        'Redux',
        'jQuery',
        'Express.js',
        'Python',
        'RESTful APIs',
        'GraphQL',
        'Microservices Architecture',
        'MongoDB',
        'MS SQL Server',
        'PostgreSQL',
        'Redis',
        'Lambda',
        'EC2',
        'S3',
        'Amplify',
        'Google Cloud Platform (GCP)',
        'Docker',
        'CI/CD Pipelines',
        'Git',
        'Test-Driven Development',
        'Code Reviews',
        'Performance Optimization',
        'Stripe API',
        'Socket.io',
        'ASP.NET',
        'AJAX',
        'Jira',
        'VS Code',
        'React Native',
        'Next.js',
        'Angular',
        'E-commerce',
        'Healthcare',
        'FinTech',
        'Agile',
        'Scrum',
        'English',
        'Hindi',
      ],
      currencyType: 'INR',
      workMode: ['remote'],
      preferredLocations: ['Bangalore', 'India'],
      location: 'Lucknow, India',
    },
  },
  {
    id: 'a39bc802-4fb5-415b-871d-23cd14c34c77',
    status: 'published',
    createdAt: '2025-09-11T15:39:26.462Z',
    candidate: {
      id: 'a39bc802-4fb5-415b-871d-23cd14c34c77',
      user: {
        id: 'd8061208-069d-4a4b-aaf6-4b5a4ec8f1f1',
        email: 'test-test16@yopmail.com',
        firstName: 'anu',
        lastName: '',
        profilePic:
          'https://faujx-dev.s3.amazonaws.com/users/d8061208-069d-4a4b-aaf6-4b5a4ec8f1f1/profile-pic/profile-pic',
      },
      roleTitle: 'Front-end',
      summary:
        'Results-oriented Senior Full Stack Developer with over 11 years of experience leading teams and delivering high-quality web and mobile applications. Proficient in React.js, Node.js, and AWS cloud technologies, with a proven track record of mentoring developers and fostering technical excellence. Skilled in managing end-to-end product development for startups, driving user engagement, and facilitating business growth through innovative solutions.',
      currentDesignation: 'frontend',
      currentCompany: '',
      expectedSalary: 15000,
      experienceYears: 0,
      skills: [],
      currencyType: 'INR',
      workMode: ['remote'],
      preferredLocations: ['Medan', 'Indonesia'],
      location: 'Lucknow, India',
    },
  },
  {
    id: 'c5328743-f04f-444c-bb54-00219d4b1431',
    status: 'published',
    createdAt: '2025-09-10T16:53:33.711Z',
    candidate: {
      id: 'c5328743-f04f-444c-bb54-00219d4b1431',
      user: {
        id: '9278da24-c53a-4558-8583-58630bc2a6e2',
        email: 'testathira2@yopmail.com',
        firstName: 'test',
        lastName: '',
        profilePic: null,
      },
      roleTitle: 'Front-end',
      summary: null,
      currentDesignation: 'frontend',
      currentCompany: '',
      expectedSalary: 0,
      experienceYears: 0,
      skills: [],
      currencyType: 'CAD',
      workMode: [],
      preferredLocations: ['Arba Minch, Ethiopia'],
      location: null,
    },
  },
  {
    id: '296b363b-9df6-469c-93c1-565b74bf8353',
    status: 'published',
    createdAt: '2025-09-10T17:02:37.634Z',
    candidate: {
      id: '296b363b-9df6-469c-93c1-565b74bf8353',
      user: {
        id: '2f89e9b3-8f23-4b38-8994-16642c72a187',
        email: 'athiratest3@yopmail.com',
        firstName: 'test',
        lastName: '',
        profilePic: null,
      },
      roleTitle: 'Front-end',
      summary: null,
      currentDesignation: 'frontend',
      currentCompany: '',
      expectedSalary: 0,
      experienceYears: 0,
      skills: [],
      currencyType: 'INR',
      workMode: ['remote'],
      preferredLocations: ['Chennai, India'],
      location: null,
    },
  },
  {
    id: '3de602fb-e6a6-4b03-b1d2-857ec60652bf',
    status: 'published',
    createdAt: '2025-09-11T14:50:45.265Z',
    candidate: {
      id: '3de602fb-e6a6-4b03-b1d2-857ec60652bf',
      user: {
        id: '979ce29d-478f-4621-ba7e-5df488ecc688',
        email: 'candidate8@yopmail.com',
        firstName: '6',
        lastName: 'Candidate',
        profilePic: null,
      },
      roleTitle: null,
      summary: null,
      currentDesignation: 'Software Engineer',
      currentCompany: 'TechCorp',
      expectedSalary: 1500000,
      experienceYears: 5,
      skills: ['NestJS', 'MongoDB', 'AWS'],
      currencyType: null,
      workMode: [],
      preferredLocations: ['Chennai', 'Bangalore', 'Remote'],
      location: null,
    },
  },
  {
    id: 'b219654f-0abd-4278-8539-d075496389a9',
    status: 'published',
    createdAt: '2025-09-11T08:10:18.823Z',
    candidate: {
      id: 'b219654f-0abd-4278-8539-d075496389a9',
      user: {
        id: 'de5c875b-f570-4986-bd93-690b31ae3462',
        email: 'candidate6@yopmail.com',
        firstName: '6',
        lastName: 'Candidate',
        profilePic: null,
      },
      roleTitle: null,
      summary: null,
      currentDesignation: 'Software Engineer',
      currentCompany: 'TechCorp',
      expectedSalary: 1500000,
      experienceYears: 5,
      skills: ['NestJS', 'MongoDB', 'AWS'],
      currencyType: null,
      workMode: [],
      preferredLocations: ['Chennai', 'Bangalore', 'Remote'],
      location: null,
    },
  },
];

// export const fake_publishedCandidates: Candidate[] = publishedCandidates.map(
//   item => item.candidate
// );
